version: '3.3'

services:

    it-tools:
        image: corentinth/it-tools:latest
        container_name: it-tools
        restart: unless-stopped
        ports:
            - "8200:80"

            